default: &default
  adapter: postgresql
  encoding: unicode
  user:
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stackoverflow_development

test:
  <<: *default
  database: stackoverflow_test

production:
  <<: *default
  database: stackoverflow_production
